### ISSUE TITLE
unhandled exception after a few seconds on startup then crash when exiting

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#723]
After a few seconds of starting springlobby, an exception popup is shown, but the lobby still works properly, apparently. Screenshot:

![sl_exception](https://cloud.githubusercontent.com/assets/11828472/15986962/aecacc1a-300f-11e6-9437-91a79319f36b.jpg)

Then it crashes when I try to exit. Screenshot:

![sl_crash_exit](https://cloud.githubusercontent.com/assets/11828472/15986965/cafda16e-300f-11e6-88b3-8b3c2e20d557.jpg)

**Comment by abma** [comment]
imo thats basicly one issue: the unhandled exception.

do you get the exception, too, when you rename your spring engine folder? (=remove all spring engines)

**Comment by springraaar** [comment]
You're right about being related, if I open the lobby then close it immediately without waiting for the exception popup, it closes normally. It only crashes if I wait for the popup before exiting.

which spring engine folder?
D:\Program Files (x86)\Spring
C:\Users\Rui\Documents\My Games\Spring\engine
C:\Users\Rui\Documents\My Games\Spring\engine\(...)  <- there are lots of engine dirs inside

I did change something in springsettings.cfg due to an error I got when trying to play ZK using zklobby (not springlobby), not sure if it's relevant

The error was this:
"""""""""
Fatal: Spring: Fatal Error (user)
duplicate base content detected:
	C:\Users\Rui\Documents\My Games\Spring\engine\101.0.1-414-g6a6a528\base\spring\
	C:\Users\Rui\Documents\My Games\Spring\engine\100.0\base\spring\
Please fix your configuration/installation as this can cause desyncs!
""""""""

which I fixed by editing the springData attribute on "C:\Users\Rui\Documents\My Games\Spring\springsettings.cfg", it's now set to 

SpringData = C:\Users\Rui\Documents\My Games\Spring

**Comment by abma** [comment]
> which spring engine folder?

all! the list in edit -> preferences -> spring must be empty as very likely one of the found spring version is causing this error.

**Comment by springraaar** [comment]
removed/renamed all :  it no longer shows exception/crash

kept 96.0 only (from original spring installation dir which is several years old) :  exception/crash shown 

kept 100.0 and 101.0.1-414-g6a.... only (these are on a new ...\Documents\My Games\Spring\engine\ directory) :  exception/crash shown

**Comment by abma** [comment]
is sth. inside unitsync.log?

is there a global springsettings.cfg? whats the content of it?

**Comment by springraaar** [comment]
C:\Users\Rui\Documents\My Games\Spring\springsettings.cfg
http://pastebin.com/ahBY1Qzn

C:\Users\Rui\Documents\My Games\Spring\unitsync.log
this one is weird, it seems it's not written to when the crash happens, or only partially, like this:

> [unitsync] deinitialized
> Spring 99.0.1-63-g2cbd0fc develop (Headless Unitsync)
> Build Environment: boost-105500, GNU libstdc++ version 20130531
> Compiler Version:  gcc-4.8.1
> Operating System:  Microsoft Windows
> Microsoft Home Premium Edition, 64-bit (build 9200)
> Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz; 8143MB RAM, 9423MB pagefile
> Word Size:         32-bit (emulated)
> Using configuration source: "C:\Users\Rui\Documents\My Games\Spring\springsettings.cfg"
> Using additional configuration source: "C:\Users\Rui\Documents\Spring\springsettings.cfg"
> Available log sections: ArchiveScanner, VFS, unitsync
> Enabled log sections: 
> Enable or disable log sections using the LogSections configuration key
>   or the SPRING_LOG_SECTIONS environment variable (both comma separated).
>   Use "none" to disable the default log sections.
> LogOutput initialized.
> Using read-write data directory: C:\Users\Rui\Documents\My Games\Spring\
> Using read-only data directory: C:\Users\Rui\Documents\Spring\
> Using read-only data directory: C:\Users\Rui\Doc

**Comment by springraaar** [comment]
Note: upgrading from 0.247 to 0.248 didn't fix this issue.

**Comment by abma** [comment]
can you paste springlobby.log please?

**Comment by abma** [comment]
also please remove the line "SpringData" from springsettings.cfg

**Comment by abma** [comment]
please test if the development version works for you:

http://springlobby.info/temp/builds/develop/sl_master.zip

**Comment by springraaar** [comment]
The application itself should not crash, at most it should show a warning that such a relevant setting is misconfigured or something.

The updated exe you provided didn't fix the issue.

Removing the "SpringData = C:\Users\Rui\Documents\My Games\Spring" from the cfg file didn't fix the issue.

where's the Springlobby.log file? can't find it.

**Comment by abma** [comment]
%APPDATA%\springlobby\springlobby.log

use wordpad / notepad++ to view it as line breaks are linux atm (#729)

**Comment by springraaar** [comment]
springlobby.log, v 0.248, SL issue 723
http://pastebin.com/t4jkKm36

springlobby.log, v 0.248-1-g04..., SL issue 723
http://pastebin.com/rXeC16vS

**Comment by abma** [comment]
looks like there is a broken game inside your data dirs:

"Warning  /data/private/buildbot/slaves/springlobby/develop-win/build/src/log.cpp:169 Error: FIXME: TDF parsing error at (EOF), on token "" : ; expected"

can you try to rename the folder games in your data dir and see if it still crashes?

**Comment by abma** [comment]
wrong... this error message is from the tdf parser which is used to parse demo files.

please try to rename the demos folder into demos2.

if this works, would be nice if you could test which file is causing this by bisecting.

when found please upload the file!

not sure if i already fixed the crash, but its VERY likely that some broken demo file causes this crash.

**Comment by abma** [comment]
please test with: http://springlobby.info/temp/builds/develop/sl_master.zip

**Comment by springraaar** [comment]
without changing the demo folder, the new executable still crashes

springlobby.log, v 0.248-3-g9c..., SL issue 723
http://pastebin.com/iatUKWiX

**Comment by springraaar** [comment]
After renaming "C:\Users\Rui\Documents\My Games\Spring\demos" to "C:\Users\Rui\Documents\My Games\Spring\demos2" it no longer crashes!

**Comment by springraaar** [comment]
that demo folder had 6k+ files, since 2013.

if i remove the latest 75, from june until now, it no longer crashes but instead hangs, probably due to processing all those replays.

**Comment by abma** [comment]
with bisecting the file could be found in arround 10 steps:

i.e.:

1. move half of the demos away
2. see if it crashes, if not use the other half.

repeat until found :)

**Comment by springraaar** [comment]
ok so i restarted the lobby, and it seems it'll take lots of time again to process the replay list, maybe it could write what it gathered into txt file and read it on startup. It's not like replays change over time (especially ones that are more than a day old).

**Comment by abma** [comment]
please test with: http://springlobby.info/temp/builds/develop/sl_master.zip (updated a few minutes ago)

added a lot of checks for decompression...

**Comment by springraaar** [comment]
the dev version behaves the same as the 0.248, exception then crash when leaving, and has the same logs. It didn't seem to show the message for the version check asking to download 0.248, as the previous ones did.

here's a zip file with 3 of the replay files that cause the problem:
http://www.filedropper.com/slissue723damagedreplays

**Comment by abma** [comment]
great, thanks! i can reproduce the crash! should be fixable now...

**Comment by abma** [comment]
can you please test again with http://springlobby.info/temp/builds/develop/sl_master.zip (updated a few hours ago)

i hopefully didn't introduce a new crash + fixed the old one.
